import { StyleSheet } from 'react-native'

export default StyleSheet.create({
  innerContainer: {
    alignItems: 'center',
    width: 292,
    height: 480,
    backgroundColor: 'white',
    borderRadius: 11,
    flexDirection: 'column',
  },
  image: {
    height: 48,
    width: 48,
    marginTop: 24,
    marginBottom: 8,
  },
  title: {
    fontStyle: 'italic',
    fontSize: 22,
    textAlign: 'center',
    lineHeight: 26,
  },
  text: {
    textAlign: 'center',
    textAlignVertical: 'center',
    width: '90%',
    alignSelf: 'center',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginTop: '4%',
    marginBottom: '3%',
    color: '#4F4F4F',
  },
  textview: {
    marginBottom: '2%',
    height: '14%',
    width: '90%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  textview2: {
    marginBottom: '2%',
    height: 40,
    width: '90%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  bold: {
    fontWeight: 'bold',
    textAlign: 'center',
    width: '90%',
    marginBottom: '2%',
  },
  italics: {
    fontSize: 19,
    fontStyle: 'italic',
    textAlign: 'center',
    textAlignVertical: 'center',
    lineHeight: 22,
    color: '#4F4F4F',
  },
  var: {
    alignSelf: 'center',
    alignItems: 'center',
    marginTop: '3%',
    marginBottom: '1%',
  },
  var2: {
    alignSelf: 'center',
    alignItems: 'center',
    marginTop: '6.5%',
    marginBottom: '5.5%',
  },
  contentWrap: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    },
})
