import { StyleSheet } from 'react-native'

export default StyleSheet.create({
  innerContainer: {
    justifyContent: 'flex-end',
    width: '100%',
    height: 390,
    backgroundColor: '#F2F2F2',
    alignSelf: 'center',
  },
  textField: {
    justifyContent: 'center',
    textAlign: 'center',
    textAlignVertical: 'center',
    marginTop: 20,
    alignSelf: 'center',
    fontSize: 24,
    alignItems: 'center',
    fontFamily: 'Circular Std',
    width: '100%',
    height: 40,
    color: '#545680',
  },
  textview: {
    justifyContent: 'center',
    alignSelf: 'center',
    alignItems: 'center',
    width: '100%',
    height: 47,
    backgroundColor: 'white',
    marginBottom: 20,
  },
  transtextField: {
    justifyContent: 'center',
    textAlign: 'center',
    alignSelf: 'center',
    fontSize: 24,
    fontFamily: 'CircularStd-Book',
    alignItems: 'center',
    width: '100%',
    marginBottom: '2%',
    height: '8%',
  },
  textContainer: {
    justifyContent: 'center',
    backgroundColor: 'white',
    alignItems: 'center',
    height: 60,
    width: '100%',
    marginBottom: 50,
    borderRadius: 5,
  },
  datePicker: {
    backgroundColor: 'white',
  },
  view: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  image: {
    width: 18,
    height: 18,
    alignSelf: 'flex-end',
    marginRight: 6,
    marginTop: 12,
  },
})
